server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: hello_route
          uri: http://localhost:8080
          predicates:
            - Path=/city-population/list
          filters:
            - name: Hystrix
              args:
                name: fallbackcmd
                # 服务熔断回调函数
                fallbackUri: forward:/fallback
            # 想请求参数中追加foo=bar
            - AddRequestParameter=foo, bar

org:
  pass:
    jwt:
      skipUrls:
        /login