server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery: #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:
          enabled: true #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
      routes:
        - id: hello_route
          uri: http://localhost:8080
          predicates:
            - Path=/api/hello
        - id: baidu
          uri: http://www.baidu.com
          predicates:
            - Path=/baidu/**
          filters:
            - name: Hystrix
              args:
                name: fallbackcmd
                # 服务熔断回调函数
                fallbackUri: forward:/fallback
            # 想请求参数中追加foo=bar
            - AddRequestParameter=foo, bar
