server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: hello_route
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/sayHello,/sayHelloFeign