
server:
  port: 8083
spring:
  application:
    name: gateway
  cloud:
    zookeeper:
      enabled: true
      connect-string: 192.168.2.136:2181
    gateway:
      routes:
        - id: hello_route
          uri: lb://user-service
          predicates:
            - Path=/city-population/list
          filters:
            - name: Hystrix
              args:
                name: fallbackcmd
                # 服务熔断回调函数
                fallbackUri: forward:/fallback
            # 想请求参数中追加foo=bar
            - AddRequestParameter=foo, bar
        - id: baidu
          uri: http://www.baidu.com
          predicates:
            - Path=/baidu/**


