server:
  port: 8088

spring:
  dubbo:
      application:
        name: order-service #应用名
      registry:
        address: zookeeper://192.168.255.128
        port: 2181 #提供注册的端口
      protocol:
        name: dubbo
        port: 20890 #dubbo服务暴露的端口
      scan: com.newbie.portal #扫描的包名
  datasource:
    name: dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.136:3306/dev
    username: wangfei
    password: wf147369
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath*:mapper/*.xml